services:
    spring-app:
      image: my-spring-app:latests
      environment:
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fast_food
      depends_on:
        - postgres
        - redis
    postgres-fast_food:
      image: postgres:16
      environment:
        POSTGRES_DB: fast_food
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    redis-fast_food:
      image: redis:7.2.4
      ports:
        - "6379:6379"



