spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres:5432/fast_food
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  otp:
    retry-wait-time: 60 # in seconds
    retry-count: 3
    time-to-live: 86400 # in seconds
notification:
  eskiz:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTY5OTQ1NzMsImlhdCI6MTcxNDQwMjU3Mywicm9sZSI6InRlc3QiLCJzaWduIjoiMmYxMDliOTRmOWE3MWM1NjNhMGRmYWQ3NTUwYmZkOTY1ZmFkMGI4ZWQzNDQxMDFjMzE0NGJhNWQ2MzQ5YmEzOCIsInN1YiI6IjU1OTEifQ.LkOpwTRtapPhtczF4cfFtnG6c--113dKrEyIDTEuxkU

security:
  token:
    expiration: 86400
    secretKey: 72d8fb249e2074c49166b401ede475acee909e8e272dbcd134dcdf744f000db3

